//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace FamilyBudgetSilverlightApp.BudgetServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetRequest", Namespace="http://schemas.datacontract.org/2004/07/FamilyBudget_ASP_MVC_APP.WcfServices.Data" +
        "Contracts")]
    public partial class GetBudgetRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int BudgetIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BudgetId {
            get {
                return this.BudgetIdField;
            }
            set {
                if ((this.BudgetIdField.Equals(value) != true)) {
                    this.BudgetIdField = value;
                    this.RaisePropertyChanged("BudgetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetResponse", Namespace="http://schemas.datacontract.org/2004/07/FamilyBudget_ASP_MVC_APP.WcfServices.Data" +
        "Contracts")]
    public partial class GetBudgetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BudgetDto", Namespace="http://schemas.datacontract.org/2004/07/FamilyBudget_ASP_MVC_APP.Dto")]
    public partial class BudgetDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BudgetServiceReference.IBudgetService")]
    public interface IBudgetService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBudgetService/GetBudget", ReplyAction="http://tempuri.org/IBudgetService/GetBudgetResponse")]
        System.IAsyncResult BeginGetBudget(FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request, System.AsyncCallback callback, object asyncState);
        
        FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse EndGetBudget(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBudgetService/GetBudgetById", ReplyAction="http://tempuri.org/IBudgetService/GetBudgetByIdResponse")]
        System.IAsyncResult BeginGetBudgetById(int budgetId, System.AsyncCallback callback, object asyncState);
        
        FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto EndGetBudgetById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBudgetServiceChannel : FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBudgetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBudgetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBudgetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBudgetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BudgetServiceClient : System.ServiceModel.ClientBase<FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService>, FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService {
        
        private BeginOperationDelegate onBeginGetBudgetDelegate;
        
        private EndOperationDelegate onEndGetBudgetDelegate;
        
        private System.Threading.SendOrPostCallback onGetBudgetCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBudgetByIdDelegate;
        
        private EndOperationDelegate onEndGetBudgetByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetBudgetByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public BudgetServiceClient() {
        }
        
        public BudgetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BudgetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetBudgetCompletedEventArgs> GetBudgetCompleted;
        
        public event System.EventHandler<GetBudgetByIdCompletedEventArgs> GetBudgetByIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService.BeginGetBudget(FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBudget(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService.EndGetBudget(System.IAsyncResult result) {
            return base.Channel.EndGetBudget(result);
        }
        
        private System.IAsyncResult OnBeginGetBudget(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request = ((FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest)(inValues[0]));
            return ((FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService)(this)).BeginGetBudget(request, callback, asyncState);
        }
        
        private object[] OnEndGetBudget(System.IAsyncResult result) {
            FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse retVal = ((FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService)(this)).EndGetBudget(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBudgetCompleted(object state) {
            if ((this.GetBudgetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBudgetCompleted(this, new GetBudgetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBudgetAsync(FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request) {
            this.GetBudgetAsync(request, null);
        }
        
        public void GetBudgetAsync(FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request, object userState) {
            if ((this.onBeginGetBudgetDelegate == null)) {
                this.onBeginGetBudgetDelegate = new BeginOperationDelegate(this.OnBeginGetBudget);
            }
            if ((this.onEndGetBudgetDelegate == null)) {
                this.onEndGetBudgetDelegate = new EndOperationDelegate(this.OnEndGetBudget);
            }
            if ((this.onGetBudgetCompletedDelegate == null)) {
                this.onGetBudgetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBudgetCompleted);
            }
            base.InvokeAsync(this.onBeginGetBudgetDelegate, new object[] {
                        request}, this.onEndGetBudgetDelegate, this.onGetBudgetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService.BeginGetBudgetById(int budgetId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBudgetById(budgetId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService.EndGetBudgetById(System.IAsyncResult result) {
            return base.Channel.EndGetBudgetById(result);
        }
        
        private System.IAsyncResult OnBeginGetBudgetById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int budgetId = ((int)(inValues[0]));
            return ((FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService)(this)).BeginGetBudgetById(budgetId, callback, asyncState);
        }
        
        private object[] OnEndGetBudgetById(System.IAsyncResult result) {
            FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto retVal = ((FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService)(this)).EndGetBudgetById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBudgetByIdCompleted(object state) {
            if ((this.GetBudgetByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBudgetByIdCompleted(this, new GetBudgetByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBudgetByIdAsync(int budgetId) {
            this.GetBudgetByIdAsync(budgetId, null);
        }
        
        public void GetBudgetByIdAsync(int budgetId, object userState) {
            if ((this.onBeginGetBudgetByIdDelegate == null)) {
                this.onBeginGetBudgetByIdDelegate = new BeginOperationDelegate(this.OnBeginGetBudgetById);
            }
            if ((this.onEndGetBudgetByIdDelegate == null)) {
                this.onEndGetBudgetByIdDelegate = new EndOperationDelegate(this.OnEndGetBudgetById);
            }
            if ((this.onGetBudgetByIdCompletedDelegate == null)) {
                this.onGetBudgetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBudgetByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetBudgetByIdDelegate, new object[] {
                        budgetId}, this.onEndGetBudgetByIdDelegate, this.onGetBudgetByIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService CreateChannel() {
            return new BudgetServiceClientChannel(this);
        }
        
        private class BudgetServiceClientChannel : ChannelBase<FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService>, FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService {
            
            public BudgetServiceClientChannel(System.ServiceModel.ClientBase<FamilyBudgetSilverlightApp.BudgetServiceReference.IBudgetService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBudget(FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetBudget", _args, callback, asyncState);
                return _result;
            }
            
            public FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse EndGetBudget(System.IAsyncResult result) {
                object[] _args = new object[0];
                FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse _result = ((FamilyBudgetSilverlightApp.BudgetServiceReference.GetBudgetResponse)(base.EndInvoke("GetBudget", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBudgetById(int budgetId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = budgetId;
                System.IAsyncResult _result = base.BeginInvoke("GetBudgetById", _args, callback, asyncState);
                return _result;
            }
            
            public FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto EndGetBudgetById(System.IAsyncResult result) {
                object[] _args = new object[0];
                FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto _result = ((FamilyBudgetSilverlightApp.BudgetServiceReference.BudgetDto)(base.EndInvoke("GetBudgetById", _args, result)));
                return _result;
            }
        }
    }
}
